version: '2'
services:

  #Only for a single instance for all DCs and nodes, to act as a leader (alternatively common backend storage?)
  munchkin-storage-leader:
    image: minio/minio:$MINIO_STABLE_TAG
    restart: always
    command: server /export
    ports:
      - "9000"    
    volumes:
      - munchkin-storage-leader:/export
    labels:
      - "traefik.backend=munchkin-storage-leader"
      - "traefik.frontend.rule=Host:munchkin-storage-leader.$DOCKER_DC.$DOCKER_BASEDOMAIN"
      - "traefik.port=9000"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.enable=true"
    container_name: munchkin-storage-leader
    environment:
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
    networks:
      - devops-back    

volumes:
  munchkin-storage-leader:
    external: true

networks:
  default:
    driver: bridge
  devops-back:
    external: true

